# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://denshochan.com
title: 電書ちゃんねる
email: info@denshochan.com
author: Hiroshi Takase a.k.a. lost_and_found
description: "あなたの思いを届けたい。電子出版を応援する任意団体「電書ちゃんねる」の公式ウェブサイト。"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

fb_app_id: 917304118299061
social:
  - title: twitter
    url: https://twitter.com/denshochan
  - title: facebook
    url: https://www.facebook.com/denshochannel
  - title: google-plus
    url: https://plus.google.com/106072295374144683246
